/* =====================================================================
   data.js — Single source of truth for Adam Roastery (محمص آدم)
   Pricing model:
     unit: "kg"    -> sold by weight, weight selector 100g..1000g,
                      `price` is the price per 1 kg.
     unit: "piece" -> sold per unit, `price` is the fixed unit price.
   Taxonomy:
     cat  -> top-level category id (see CATEGORIES)
     sub  -> optional subcategory id (must exist in that category's `subs`)
   Each product carries a bilingual { ar, he } name and desc.
   Images live in assets/images/<category>/<file>.
   ===================================================================== */
(function () {
  "use strict";

  const STORE = {
    name: { ar: "محمص آدم", he: "פיצוחי אדם" },
    tagline: {
      ar: "أجود أنواع التمور والمكسرات الفاخرة",
      he: "מבחר התמרים והפיצוחים המשובחים ביותר"
    },
    whatsapp: "972523305309",            // wa.me number (no +)
    whatsappDisplay: "052-330-5309",
    location: "https://share.google/GE8DXfe1LgktsaNbT",
    // 👉 The public URL the menu QR code points to. After deploying, set this to
    //    your live URL, then regenerate assets/images/qr-menu.svg with any free
    //    online QR generator (no build tools / Node required).
    menuUrl: "https://adam-roastery.netlify.app",
    developer: { name: "O&H Tech", url: "https://oh-tech.co" }
  };

  // Weight options in grams for kg-unit products
  const WEIGHTS = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];

  // Reusable subcategory definitions
  const SUB = {
    treeNuts: { id: "tree-nuts", name: { ar: "مكسرات", he: "אגוזים" } },
    seeds:    { id: "seeds",     name: { ar: "بذور", he: "גרעינים" } },
    legumes:  { id: "legumes",   name: { ar: "بقوليات", he: "קטניות" } },
    ground:   { id: "ground",    name: { ar: "مطحون", he: "טחון" } },
    whole:    { id: "whole",     name: { ar: "حبوب", he: "גרגרים" } },
    blends:   { id: "blends",    name: { ar: "خلطات", he: "תערובות" } },
    medjool:  { id: "medjool",   name: { ar: "مجدول", he: "מג'הול" } },
    soft:     { id: "soft",      name: { ar: "طري", he: "רך" } },
    stuffed:  { id: "stuffed",   name: { ar: "محشي", he: "ממולא" } }
  };

  const CATEGORIES = [
    { id: "nuts",         name: { ar: "مكسرات",        he: "פיצוחים" },         img: "assets/images/nuts/nuts-7.jpeg",
      subs: [SUB.treeNuts, SUB.seeds, SUB.legumes] },
    { id: "natural-nuts", name: { ar: "مكسرات طبيعية", he: "פיצוחים טבעיים" },  img: "assets/images/natural-nuts/natural-nuts-5.jpeg" },
    { id: "dates",        name: { ar: "تمور",          he: "תמרים" },           img: "assets/images/dried/dried-2.jpeg",
      subs: [SUB.medjool, SUB.soft, SUB.stuffed] },  // structure ready for more date types
    { id: "dried",        name: { ar: "فواكه مجففة",   he: "פירות יבשים" },     img: "assets/images/dried/dried-5.jpeg" },
    { id: "spices",       name: { ar: "بهارات",        he: "תבלינים" },         img: "assets/images/spices/spices-1.png",
      subs: [SUB.ground, SUB.whole, SUB.blends] },
    { id: "coffee",       name: { ar: "قهوة",          he: "קפה" },             img: "assets/images/coffee/coffee-1.jpeg" },
    { id: "espresso",     name: { ar: "إسبريسو",       he: "אספרסו" },          img: "assets/images/espresso/espresso-9.jpeg" },
    { id: "sweets",       name: { ar: "حلويات",        he: "מתוקים" },          img: "assets/images/sweets/sweets-2.jpeg" },
    { id: "snacks",       name: { ar: "حلويات خفيفة",  he: "חטיפים" },          img: "assets/images/snacks/snacks-4.jpeg" },
    { id: "gummy",        name: { ar: "حلوى جيلي",     he: "סוכריות גומי" },    img: "assets/images/gummy/gummy-19.jpeg" }
  ];

  const im = (cat, file) => `assets/images/${cat}/${file}`;

  const PRODUCTS = [
    /* ---------------- NUTS (by weight) ---------------- */
    { id: "nuts-1",  cat: "nuts", sub: "seeds",     unit: "kg", price: 30,  img: im("nuts","nuts-1.jpeg"),
      name: { ar: "بزر أسود مملح", he: "גרעינים שחורים מלוחים" },
      desc: { ar: "بزر عبّاد الشمس الأسود المحمّص والمملّح، مقرمش ولذيذ للتسالي.", he: "גרעיני חמנייה שחורים קלויים ומלוחים, פריכים וטעימים לנשנוש." } },
    { id: "nuts-2",  cat: "nuts", sub: "seeds",     unit: "kg", price: 30,  img: im("nuts","nuts-2.jpeg"),
      name: { ar: "بزر أسود غير مملح", he: "גרעינים שחורים ללא מלח" },
      desc: { ar: "بزر أسود محمّص بدون ملح، خيار صحي ومثالي للتسالي اليومية.", he: "גרעינים שחורים קלויים ללא מלח, בחירה בריאה לנשנוש יומיומי." } },
    { id: "nuts-3",  cat: "nuts", sub: "seeds",     unit: "kg", price: 50,  img: im("nuts","nuts-3.jpeg"),
      name: { ar: "بزر بطيخ", he: "גרעיני אבטיח" },
      desc: { ar: "بزر البطيخ المحمّص بنكهته الغنية وقيمته الغذائية العالية.", he: "גרעיני אבטיח קלויים, טעם עשיר וערך תזונתי גבוה." } },
    { id: "nuts-4",  cat: "nuts", sub: "seeds",     unit: "kg", price: 45,  img: im("nuts","nuts-4.jpeg"),
      name: { ar: "بزر قرع", he: "גרעיני דלעת" },
      desc: { ar: "بزر اليقطين المحمّص، غني بالبروتين ومثالي للوجبات الخفيفة.", he: "גרעיני דלעת קלויים, עשירים בחלבון ומושלמים לנשנוש." } },
    { id: "nuts-5",  cat: "nuts", sub: "tree-nuts", unit: "kg", price: 35,  img: im("nuts","nuts-5.jpeg"),
      name: { ar: "بندق أمريكي", he: "אגוזי לוז אמריקאי" },
      desc: { ar: "بندق أمريكي محمّص بقشره، نكهة كلاسيكية وقرمشة مميّزة.", he: "אגוזי לוז אמריקאי קלויים בקליפתם, טעם קלאסי ופריכות מיוחדת." } },
    { id: "nuts-6",  cat: "nuts", sub: "tree-nuts", unit: "kg", price: 80,  img: im("nuts","nuts-6.jpeg"),
      name: { ar: "بندق مملح", he: "אגוזי לוז מלוחים" },
      desc: { ar: "بندق محمّص ومملّح بعناية، غني بالنكهة ومثالي للضيافة.", he: "אגוזי לוז קלויים ומלוחים בקפידה, עשירים בטעם ומושלמים לאירוח." } },
    { id: "nuts-7",  cat: "nuts", sub: "tree-nuts", unit: "kg", price: 80,  img: im("nuts","nuts-7.jpeg"), bestseller: true,
      name: { ar: "جوز فاخر", he: "אגוזי מלך משובחים" },
      desc: { ar: "عين جوز كاملة فاخرة، طازجة ومقرمشة بطعم غني ومميّز.", he: "אגוזי מלך שלמים ומשובחים, טריים ופריכים בטעם עשיר." } },
    { id: "nuts-8",  cat: "nuts", sub: "legumes",   unit: "kg", price: 45,  img: im("nuts","nuts-8.jpeg"),
      name: { ar: "حمص محمّص", he: "חומוס קלוי" },
      desc: { ar: "حمص محمّص ذهبي مقرمش، تسالي شعبية أصيلة ولذيذة.", he: "חומוס קלוי זהוב ופריך, נשנוש מסורתי אותנטי וטעים." } },
    { id: "nuts-9",  cat: "nuts", sub: "legumes",   unit: "kg", price: 50,  img: im("nuts","nuts-9.jpeg"),
      name: { ar: "رفيولي", he: "רביולי" },
      desc: { ar: "رفيولي مقرمش بطبقة خارجية ذهبية ونكهة لا تُقاوم.", he: "רביולי פריך בציפוי זהוב וטעם שאי אפשר לעמוד בפניו." } },
    { id: "nuts-10", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 70,  img: im("nuts","nuts-10.jpeg"), bestseller: true, offer: 10,
      name: { ar: "فستق حلبي فاخر", he: "פיסטוק חלבי משובח" },
      desc: { ar: "فستق حلبي فاخر محمّص ومملّح، ملكة المكسرات بطعمها الغني.", he: "פיסטוק חלבי משובח, קלוי ומלוח — מלכת הפיצוחים בטעם עשיר." } },
    { id: "nuts-11", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 35,  img: im("nuts","nuts-11.jpeg"),
      name: { ar: "فستق عبّيدي", he: "פיסטוק עבידי" },
      desc: { ar: "فستق عبّيدي محمّص بنكهته المميّزة وسعره الاقتصادي.", he: "פיסטוק עבידי קלוי בטעם מיוחד ובמחיר משתלם." } },
    { id: "nuts-12", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 50,  img: im("nuts","nuts-12.jpeg"),
      name: { ar: "كابوكيم", he: "קבוקים" },
      desc: { ar: "كابوكيم تركي محمّص بقشرة مقرمشة وطعم غني.", he: "קבוקים טורקי קלוי בקליפה פריכה וטעם עשיר." } },
    { id: "nuts-13", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 70,  img: im("nuts","nuts-13.jpeg"), bestseller: true,
      name: { ar: "كاجو محمّص فاخر", he: "קשיו קלוי משובח" },
      desc: { ar: "كاجو محمّص ذهبي بقوام كريمي ونكهة فاخرة.", he: "קשיו קלוי זהוב במרקם קרמי וטעם משובח." } },
    { id: "nuts-14", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 70,  img: im("nuts","nuts-14.jpeg"), bestseller: true,
      name: { ar: "لوز أمريكي فاخر", he: "שקדים אמריקאים משובחים" },
      desc: { ar: "لوز أمريكي محمّص بحجمه الكبير وطعمه المقرمش الغني.", he: "שקדים אמריקאים קלויים, גדולים, פריכים וטעימים." } },
    { id: "nuts-15", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 120, img: im("nuts","nuts-15.jpeg"),
      name: { ar: "مكاديميا محمّصة", he: "מקדמיה קלויה" },
      desc: { ar: "مكاديميا محمّصة فاخرة بقوام زبدي ونكهة استثنائية.", he: "מקדמיה קלויה משובחת במרקם חמאתי וטעם יוצא דופן." } },
    { id: "nuts-16", cat: "nuts", sub: "tree-nuts", unit: "kg", price: 80,  img: im("nuts","nuts-16.jpeg"),
      name: { ar: "مكاديميا مع قشر", he: "מקדמיה עם קליפה" },
      desc: { ar: "مكاديميا بقشرها الطبيعي، طازجة وغنية بالنكهة.", he: "מקדמיה עם קליפתה הטבעית, טרייה ועשירה בטעם." } },

    /* ---------------- NATURAL NUTS (by weight) ---------------- */
    { id: "nat-1", cat: "natural-nuts", unit: "kg", price: 45,  img: im("natural-nuts","natural-nuts-1.jpeg"),
      name: { ar: "بزر قرع مقشّر", he: "גרעיני דלעת קלופים" },
      desc: { ar: "حب قرع مقشّر طبيعي، جاهز للأكل وغني بالعناصر الغذائية.", he: "גרעיני דלעת קלופים טבעיים, מוכנים לאכילה ועשירים בערכים." } },
    { id: "nat-2", cat: "natural-nuts", unit: "kg", price: 70,  img: im("natural-nuts","natural-nuts-2.jpeg"),
      name: { ar: "جوز بيكان", he: "פקאן" },
      desc: { ar: "جوز بيكان طبيعي بنكهة حلوة ناعمة وقوام مقرمش.", he: "פקאן טבעי בטעם מתקתק עדין ומרקם פריך." } },
    { id: "nat-3", cat: "natural-nuts", unit: "kg", price: 120, img: im("natural-nuts","natural-nuts-3.jpeg"), offer: 10,
      name: { ar: "صنوبر", he: "צנובר" },
      desc: { ar: "صنوبر فاخر طبيعي، إضافة راقية للأطباق والحلويات.", he: "צנובר משובח טבעי, תוספת יוקרתית למנות ולקינוחים." } },
    { id: "nat-4", cat: "natural-nuts", unit: "kg", price: 40,  img: im("natural-nuts","natural-nuts-4.jpeg"),
      name: { ar: "عين الشمس مقشّر", he: "גרעיני חמנייה קלופים" },
      desc: { ar: "لب عبّاد الشمس المقشّر، خفيف وصحي وسهل التناول.", he: "גרעיני חמנייה קלופים, קלים, בריאים ונוחים לאכילה." } },
    { id: "nat-5", cat: "natural-nuts", unit: "kg", price: 120, img: im("natural-nuts","natural-nuts-5.jpeg"),
      name: { ar: "فستق حلبي مقشّر", he: "פיסטוק חלבי קלוף" },
      desc: { ar: "حب فستق حلبي مقشّر بلونه الأخضر الزاهي ونكهته الفاخرة.", he: "פיסטוק חלבי קלוף בצבע ירוק עז ובטעם משובח." } },
    { id: "nat-6", cat: "natural-nuts", unit: "kg", price: 65,  img: im("natural-nuts","natural-nuts-6.jpeg"),
      name: { ar: "كاجو مقشّر", he: "קשיו קלוף" },
      desc: { ar: "كاجو طبيعي مقشّر نيء، مثالي للطبخ والتزيين.", he: "קשיו טבעי קלוף, מושלם לבישול ולקישוט." } },
    { id: "nat-7", cat: "natural-nuts", unit: "kg", price: 60,  img: im("natural-nuts","natural-nuts-7.jpeg"),
      name: { ar: "لوز طبيعي", he: "שקדים טבעיים" },
      desc: { ar: "لوز طبيعي نيء بقشرته البنية، صحي ومتعدد الاستخدامات.", he: "שקדים טבעיים עם קליפתם החומה, בריאים ורב-שימושיים." } },
    { id: "nat-8", cat: "natural-nuts", unit: "kg", price: 60,  img: im("natural-nuts","natural-nuts-8.jpeg"),
      name: { ar: "لوز مقطّع أرباع", he: "שקדים חתוכים לרבעים" },
      desc: { ar: "لوز مقطّع أرباع جاهز للخَبز والطبخ والتزيين.", he: "שקדים חתוכים לרבעים, מוכנים לאפייה, בישול וקישוט." } },
    { id: "nat-9", cat: "natural-nuts", unit: "kg", price: 60,  img: im("natural-nuts","natural-nuts-9.jpeg"),
      name: { ar: "لوز مقطّع أنصاف", he: "שקדים חצויים" },
      desc: { ar: "لوز مقطّع أنصاف مثالي للحلويات والمعجنات.", he: "שקדים חצויים, מושלמים לקינוחים ולמאפים." } },

    /* ---------------- DATES (by weight) ---------------- */
    { id: "date-1", cat: "dates", sub: "medjool", unit: "kg", price: 45, img: im("dried","dried-2.jpeg"), bestseller: true,
      name: { ar: "تمر مجدول فاخر", he: "תמר מג'הול משובח" },
      desc: { ar: "تمر مجدول فاخر طري وغني بالسكر الطبيعي، حبّات كبيرة ممتلئة.", he: "תמר מג'הול משובח, רך ועשיר בסוכר טבעי, פרי גדול ומלא." } },

    /* ---------------- DRIED FRUITS (by weight) ---------------- */
    { id: "dry-1", cat: "dried", unit: "kg", price: 50, img: im("dried","dried-1.jpeg"),
      name: { ar: "أناناس مجفّف", he: "אננס מיובש" },
      desc: { ar: "شرائح أناناس مجفّفة بنكهة استوائية حلوة ومنعشة.", he: "פרוסות אננס מיובש בטעם טרופי מתוק ומרענן." } },
    { id: "dry-3", cat: "dried", unit: "kg", price: 55, img: im("dried","dried-3.jpeg"),
      name: { ar: "زبيب", he: "צימוקים" },
      desc: { ar: "زبيب طبيعي حلو، مثالي للتسالي والخَبز والطبخ.", he: "צימוקים טבעיים ומתוקים, מושלמים לנשנוש, אפייה ובישול." } },
    { id: "dry-4", cat: "dried", unit: "kg", price: 60, img: im("dried","dried-4.jpeg"),
      name: { ar: "عين البقرة (خوخ)", he: "שזיפים מיובשים" },
      desc: { ar: "خوخ مجفّف طري بنكهة غنية وفوائد غذائية عالية.", he: "שזיפים מיובשים רכים בטעם עשיר ובערך תזונתי גבוה." } },
    { id: "dry-5", cat: "dried", unit: "kg", price: 65, img: im("dried","dried-5.jpeg"),
      name: { ar: "قطين (تين مجفّف)", he: "תאנים מיובשות" },
      desc: { ar: "تين مجفّف طبيعي حلو المذاق وغني بالألياف.", he: "תאנים מיובשות טבעיות, מתוקות ועשירות בסיבים." } },
    { id: "dry-6", cat: "dried", unit: "kg", price: 60, img: im("dried","dried-6.jpeg"),
      name: { ar: "مشمش مجفّف", he: "משמש מיובש" },
      desc: { ar: "مشمش مجفّف بلونه الذهبي ونكهته الحلوة الحامضة.", he: "משמש מיובש בצבע זהוב ובטעם מתוק-חמצמץ." } },

    /* ---------------- SPICES (by weight) ---------------- */
    { id: "spc-1",  cat: "spices", sub: "ground", unit: "kg", price: 50,  img: im("spices","spices-1.png"),
      name: { ar: "بابريكا حارّة", he: "פפריקה חריפה" },
      desc: { ar: "بابريكا حمراء حارّة تضيف لوناً ونكهة ناريّة لأطباقك.", he: "פפריקה אדומה חריפה שמוסיפה צבע וטעם לוהט למנות." } },
    { id: "spc-2",  cat: "spices", sub: "ground", unit: "kg", price: 50,  img: im("spices","spices-2.png"),
      name: { ar: "بابريكا حلوة", he: "פפריקה מתוקה" },
      desc: { ar: "بابريكا حمراء حلوة بنكهة معتدلة ولون شهي.", he: "פפריקה אדומה מתוקה בטעם עדין ובצבע מפתה." } },
    { id: "spc-3",  cat: "spices", sub: "ground", unit: "kg", price: 55,  img: im("spices","spices-3.png"),
      name: { ar: "بابريكا مدخّنة", he: "פפריקה מעושנת" },
      desc: { ar: "بابريكا مدخّنة بنكهة عميقة تمنح الأطباق طابعاً مميّزاً.", he: "פפריקה מעושנת בטעם עמוק שמעניק למנות אופי מיוחד." } },
    { id: "spc-4",  cat: "spices", sub: "whole",  unit: "kg", price: 70,  img: im("spices","spices-4.png"),
      name: { ar: "بهار أبو ريحة حب", he: "פלפל אנגלי גרגרים" },
      desc: { ar: "بهار أبو ريحة (البهار الحلو) حب كامل لنكهة عطرية دافئة.", he: "פלפל אנגלי גרגרים שלמים לטעם ארומטי וחמים." } },
    { id: "spc-5",  cat: "spices", sub: "ground", unit: "kg", price: 70,  img: im("spices","spices-5.jpeg"),
      name: { ar: "بهار أبو ريحة مطحون", he: "פלפל אנגלי טחון" },
      desc: { ar: "بهار أبو ريحة مطحون ناعم، عطري ومثالي للتتبيل.", he: "פלפל אנגלי טחון דק, ארומטי ומושלם לתיבול." } },
    { id: "spc-6",  cat: "spices", sub: "blends", unit: "kg", price: 60,  img: im("spices","spices-6.jpeg"),
      name: { ar: "بهار دجاج", he: "תבלין לעוף" },
      desc: { ar: "خلطة بهارات الدجاج المتوازنة لمذاق غني وشهي.", he: "תערובת תבלינים לעוף, מאוזנת לטעם עשיר ומשובח." } },
    { id: "spc-7",  cat: "spices", sub: "blends", unit: "kg", price: 60,  img: im("spices","spices-7.jpeg"),
      name: { ar: "بهار شاورما", he: "תבלין שווארמה" },
      desc: { ar: "خلطة بهارات الشاورما الأصيلة بنكهتها الشرقية المميّزة.", he: "תערובת תבליני שווארמה אותנטית בטעם מזרחי מובהק." } },
    { id: "spc-8",  cat: "spices", sub: "blends", unit: "kg", price: 65,  img: im("spices","spices-8.webp"),
      name: { ar: "بهار كاري", he: "קארי" },
      desc: { ar: "كاري أصفر عطري بخلطة توابل غنية ومتوازنة.", he: "קארי צהוב ארומטי בתערובת תבלינים עשירה ומאוזנת." } },
    { id: "spc-9",  cat: "spices", sub: "blends", unit: "kg", price: 60,  img: im("spices","spices-9.jpeg"),
      name: { ar: "بهار للطبخ", he: "תערובת תבלינים לבישול" },
      desc: { ar: "خلطة بهارات شاملة لجميع أنواع الطبخ اليومي.", he: "תערובת תבלינים כללית לכל סוגי הבישול היומיומי." } },
    { id: "spc-10", cat: "spices", sub: "blends", unit: "kg", price: 60,  img: im("spices","spices-10.jpeg"),
      name: { ar: "بهار مقلوبة", he: "תבלין למקלובה" },
      desc: { ar: "خلطة بهارات المقلوبة لنكهة شرقية أصيلة لا تُنسى.", he: "תערובת תבלינים למקלובה לטעם מזרחי אותנטי ובלתי נשכח." } },
    { id: "spc-11", cat: "spices", sub: "ground", unit: "kg", price: 60,  img: im("spices","spices-11.jpeg"),
      name: { ar: "تشيلي حارّ", he: "צ'ילי חריף" },
      desc: { ar: "فلفل تشيلي حارّ مطحون يضيف حرارة ونكهة قويّة.", he: "צ'ילי חריף טחון שמוסיף חריפות וטעם עוצמתי." } },
    { id: "spc-12", cat: "spices", sub: "ground", unit: "kg", price: 120, img: im("spices","spices-12.jpeg"),
      name: { ar: "جوز الطيب مطحون", he: "אגוז מוסקט טחון" },
      desc: { ar: "جوز الطيب المطحون بنكهته الدافئة المثالية للحلويات.", he: "אגוז מוסקט טחון בטעם חמים, מושלם לקינוחים." } },
    { id: "spc-13", cat: "spices", sub: "ground", unit: "kg", price: 70,  img: im("spices","spices-13.jpeg"),
      name: { ar: "زنجبيل مطحون", he: "ג'ינג'ר טחון" },
      desc: { ar: "زنجبيل مطحون بنكهة حارّة منعشة للطبخ والمشروبات.", he: "ג'ינג'ר טחון בטעם חריף ומרענן לבישול ולמשקאות." } },
    { id: "spc-14", cat: "spices", sub: "ground", unit: "kg", price: 50,  img: im("spices","spices-14.jpeg"),
      name: { ar: "سمّاق", he: "סומק" },
      desc: { ar: "سمّاق أحمر بنكهة حامضة منعشة، أساسي للمسخّن والسلطات.", he: "סומק אדום בטעם חמצמץ מרענן, חיוני למוסחן ולסלטים." } },
    { id: "spc-15", cat: "spices", sub: "whole",  unit: "kg", price: 90,  img: im("spices","spices-15.jpeg"),
      name: { ar: "فلفل أسود حب", he: "פלפל שחור גרגרים" },
      desc: { ar: "فلفل أسود حب كامل لنكهة طازجة عند الطحن.", he: "פלפל שחור גרגרים שלמים לטעם טרי בעת הטחינה." } },
    { id: "spc-16", cat: "spices", sub: "ground", unit: "kg", price: 90,  img: im("spices","spices-16.jpeg"),
      name: { ar: "فلفل أسود خشن", he: "פלפל שחור גס" },
      desc: { ar: "فلفل أسود مجروش خشن لنكهة قويّة وملمس مميّز.", he: "פלפל שחור גרוס גס לטעם עז ולמרקם מיוחד." } },
    { id: "spc-17", cat: "spices", sub: "ground", unit: "kg", price: 90,  img: im("spices","spices-17.jpeg"),
      name: { ar: "فلفل أسود مطحون", he: "פלפל שחור טחון" },
      desc: { ar: "فلفل أسود مطحون ناعم، أساسي في كل مطبخ.", he: "פלפל שחור טחון דק, בסיסי בכל מטבח." } },
    { id: "spc-18", cat: "spices", sub: "whole",  unit: "kg", price: 100, img: im("spices","spices-18.jpeg"),
      name: { ar: "فلفل حب ألوان", he: "פלפל צבעוני גרגרים" },
      desc: { ar: "خليط فلفل ملوّن بحبّاته الكاملة لنكهة ومظهر مميّز.", he: "תערובת פלפל צבעוני בגרגרים שלמים לטעם ומראה מיוחד." } },
    { id: "spc-19", cat: "spices", sub: "whole",  unit: "kg", price: 50,  img: im("spices","spices-19.webp"),
      name: { ar: "قرفة عيدان", he: "קינמון מקלות" },
      desc: { ar: "أعواد قرفة طبيعية عطرية للمشروبات والطبخ.", he: "מקלות קינמון טבעיים וארומטיים למשקאות ולבישול." } },
    { id: "spc-20", cat: "spices", sub: "ground", unit: "kg", price: 50,  img: im("spices","spices-20.jpeg"),
      name: { ar: "قرفة مطحونة", he: "קינמון טחון" },
      desc: { ar: "قرفة مطحونة ناعمة بنكهتها الدافئة الحلوة.", he: "קינמון טחון דק בטעם חמים ומתוק." } },
    { id: "spc-21", cat: "spices", sub: "whole",  unit: "kg", price: 120, img: im("spices","spices-21.webp"),
      name: { ar: "قرنفل حب", he: "ציפורן שלם" },
      desc: { ar: "قرنفل حب كامل عطري للطبخ والمشروبات الساخنة.", he: "ציפורן שלם וארומטי לבישול ולמשקאות חמים." } },
    { id: "spc-22", cat: "spices", sub: "ground", unit: "kg", price: 120, img: im("spices","spices-22.jpeg"),
      name: { ar: "قرنفل مطحون", he: "ציפורן טחון" },
      desc: { ar: "قرنفل مطحون بنكهة قويّة عطرية مثالية للحلويات.", he: "ציפורן טחון בטעם עז וארומטי, מושלם לקינוחים." } },
    { id: "spc-23", cat: "spices", sub: "ground", unit: "kg", price: 60,  img: im("spices","spices-23.webp"),
      name: { ar: "كركم مطحون", he: "כורכום טחון" },
      desc: { ar: "كركم مطحون بلونه الذهبي وفوائده الصحية العديدة.", he: "כורכום טחון בצבע זהוב ובסגולות בריאות רבות." } },
    { id: "spc-24", cat: "spices", sub: "ground", unit: "kg", price: 50,  img: im("spices","spices-24.jpeg"),
      name: { ar: "كزبرة مطحونة", he: "כוסברה טחונה" },
      desc: { ar: "كزبرة مطحونة بنكهة حمضية منعشة للطبخ والتتبيل.", he: "כוסברה טחונה בטעם הדרי מרענן לבישול ולתיבול." } },
    { id: "spc-25", cat: "spices", sub: "whole",  unit: "kg", price: 25,  img: im("spices","spices-25.jpeg"),
      name: { ar: "ملح الهيمالايا", he: "מלח הימלאיה" },
      desc: { ar: "ملح هيمالايا وردي طبيعي غني بالمعادن.", he: "מלח הימלאיה ורוד טבעי, עשיר במינרלים." } },
    { id: "spc-26", cat: "spices", sub: "ground", unit: "kg", price: 40,  img: im("spices","spices-26.png"),
      name: { ar: "ملح ليمون", he: "מלח לימון" },
      desc: { ar: "ملح ليمون (حامض الستريك) لإضافة حموضة منعشة.", he: "מלח לימון (חומצה ציטרית) להוספת חמיצות מרעננת." } },
    { id: "spc-27", cat: "spices", sub: "whole",  unit: "kg", price: 60,  img: im("spices","spices-27.png"),
      name: { ar: "ورق غار", he: "עלי דפנה" },
      desc: { ar: "ورق غار عطري يمنح الأطباق نكهة عميقة مميّزة.", he: "עלי דפנה ארומטיים שמעניקים למנות טעם עמוק ומיוחד." } },

    /* ---------------- COFFEE (by weight) ---------------- */
    { id: "cof-1", cat: "coffee", unit: "kg", price: 75, img: im("coffee","coffee-1.jpeg"), bestseller: true,
      name: { ar: "قهوة آدم العربية", he: "קפה אדם ערבי" },
      desc: { ar: "قهوة آدم العربية المحمّصة بخلطة الهيل الفاخرة، نكهة أصيلة.", he: "קפה אדם ערבי קלוי בתערובת הל משובחת, טעם אותנטי." } },

    /* ---------------- ESPRESSO (per piece) ---------------- */
    { id: "esp-1",  cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-1.png"),
      name: { ar: "كبسولات بلاك لماكينة كلوب", he: "קפסולות בלאק למכונת קלאב" },
      desc: { ar: "كبسولات إسبريسو قويّة لماكينة كلوب بنكهة غنية.", he: "קפסולות אספרסו עוצמתי למכונת קלאב בטעם עשיר." } },
    { id: "esp-2",  cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-2.png"),
      name: { ar: "كبسولات ديليتسيوسو", he: "קפסולות דליציוסו" },
      desc: { ar: "كبسولات إسبريسو ناعمة متوازنة لماكينة كلوب.", he: "קפסולות אספרסו עדין ומאוזן למכונת קלאב." } },
    { id: "esp-3",  cat: "espresso", unit: "piece", price: 50,  img: im("espresso","espresso-3.jpeg"),
      name: { ar: "لافازا إنتينسو", he: "לוואצה אינטנסו" },
      desc: { ar: "كبسولات لافازا إنتينسو بنكهة مكثّفة وكريما غنية.", he: "קפסולות לוואצה אינטנסו בטעם מרוכז וקרמה עשירה." } },
    { id: "esp-5",  cat: "espresso", unit: "piece", price: 90,  img: im("espresso","espresso-5.jpeg"),
      name: { ar: "لافازا فورتي", he: "לוואצה פורטה" },
      desc: { ar: "كبسولات لافازا فورتي القويّة لعشّاق القهوة المركّزة.", he: "קפסולות לוואצה פורטה עוצמתיות לחובבי קפה מרוכז." } },
    { id: "esp-6",  cat: "espresso", unit: "piece", price: 90,  img: im("espresso","espresso-6.jpeg"),
      name: { ar: "لافازا بيانو", he: "לוואצה פיאנו" },
      desc: { ar: "كبسولات لافازا بيانو الناعمة بنكهة لطيفة ومتوازنة.", he: "קפסולות לוואצה פיאנו עדינות בטעם נעים ומאוזן." } },
    { id: "esp-7",  cat: "espresso", unit: "piece", price: 50,  img: im("espresso","espresso-7.png"),
      name: { ar: "لافازا كريما", he: "לוואצה קרמה" },
      desc: { ar: "كبسولات لافازا كريما بطبقة كريما غنية وكثيفة.", he: "קפסולות לוואצה קרמה עם שכבת קרמה עשירה." } },
    { id: "esp-8",  cat: "espresso", unit: "piece", price: 300, img: im("espresso","espresso-8.jpeg"),
      name: { ar: "ماكينة قهوة Omor", he: "מכונת קפה Omor" },
      desc: { ar: "ماكينة قهوة Omor عملية وأنيقة لإسبريسو منزلي مثالي.", he: "מכונת קפה Omor מעשית ואלגנטית לאספרסו ביתי מושלם." } },
    { id: "esp-9",  cat: "espresso", unit: "piece", price: 400, img: im("espresso","espresso-9.jpeg"),
      name: { ar: "ماكينة قهوة لافازا", he: "מכונת קפה לוואצה" },
      desc: { ar: "ماكينة قهوة لافازا احترافية لإسبريسو بجودة المقاهي.", he: "מכונת קפה לוואצה מקצועית לאספרסו באיכות בתי קפה." } },
    { id: "esp-10", cat: "espresso", unit: "piece", price: 380, img: im("espresso","espresso-10.png"),
      name: { ar: "ماكينة قهوة كلوب", he: "מכונת קפה קלאב" },
      desc: { ar: "ماكينة قهوة كلوب متعدّدة الكبسولات بتصميم عصري.", he: "מכונת קפה קלאב רב-קפסולות בעיצוב מודרני." } },
    { id: "esp-11", cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-11.png"),
      name: { ar: "كبسولات باسو", he: "קפסולות פאסו" },
      desc: { ar: "كبسولات باسو إسبريسو لماكينة كلوب بنكهة متوازنة.", he: "קפסולות פאסו אספרסו למכונת קלאב בטעם מאוזן." } },
    { id: "esp-12", cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-12.jpeg"),
      name: { ar: "كبسولات كابتشينو", he: "קפסולות קפוצ'ינו" },
      desc: { ar: "كبسولات كابتشينو كريمية لماكينة كلوب بمذاق غني.", he: "קפסולות קפוצ'ינו קרמיות למכונת קלאב בטעם עשיר." } },
    { id: "esp-14", cat: "espresso", unit: "piece", price: 80,  img: im("espresso","espresso-14.png"),
      name: { ar: "قهوة سيجافريدو", he: "קפה סגפרדו" },
      desc: { ar: "قهوة سيجافريدو الإيطالية الفاخرة بنكهتها العريقة.", he: "קפה סגפרדו האיטלקי המשובח בטעמו המסורתי." } },
    { id: "esp-15", cat: "espresso", unit: "piece", price: 50,  img: im("espresso","espresso-15.jpeg"),
      name: { ar: "كبسولات S", he: "קפסולות S" },
      desc: { ar: "كبسولات إسبريسو متوافقة بنكهة غنية واقتصادية.", he: "קפסולות אספרסו תואמות בטעם עשיר ובמחיר משתלם." } },
    { id: "esp-16", cat: "espresso", unit: "piece", price: 20,  img: im("espresso","espresso-16.jpg"),
      name: { ar: "كبسولات دولتشي جوستو", he: "קפסולות דולצ'ה גוסטו" },
      desc: { ar: "كبسولات دولتشي جوستو متنوّعة لمشروبات قهوة متعدّدة.", he: "קפסולות דולצ'ה גוסטו מגוונות למשקאות קפה שונים." } },
    { id: "esp-20", cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-20.png"),
      name: { ar: "كبسولات نسبريسو", he: "קפסולות נספרסו" },
      desc: { ar: "كبسولات متوافقة مع نسبريسو بنكهة إسبريسو غنية.", he: "קפסולות תואמות נספרסו בטעם אספרסו עשיר." } },
    { id: "esp-23", cat: "espresso", unit: "piece", price: 18,  img: im("espresso","espresso-23.jpeg"),
      name: { ar: "كبسولات شوكولاتة لماكينة كلوب", he: "קפסולות שוקולד למכונת קלאב" },
      desc: { ar: "كبسولات مشروب الشوكولاتة الساخنة لماكينة كلوب.", he: "קפסולות שוקו חם למכונת קלאב." } },
    { id: "esp-24", cat: "espresso", unit: "piece", price: 120, img: im("espresso","espresso-24.jpeg"),
      name: { ar: "سوبر كريما", he: "סופר קרמה" },
      desc: { ar: "خليط سوبر كريما لإسبريسو بطبقة كريما كثيفة ومثالية.", he: "תערובת סופר קרמה לאספרסו עם שכבת קרמה עשירה." } },

    /* ---------------- SWEETS (per piece / package) ---------------- */
    { id: "swt-1", cat: "sweets", unit: "piece", price: 70,  img: im("sweets","sweets-1.jpeg"),
      name: { ar: "برازق حبيبة 700غ", he: "בראזק חביבה 700 גרם" },
      desc: { ar: "برازق حبيبة بالسمسم والفستق، حلوى شامية مقرمشة فاخرة.", he: "בראזק חביבה עם שומשום ופיסטוק, מתוק שאמי פריך ומשובח." } },
    { id: "swt-2", cat: "sweets", unit: "piece", price: 150, img: im("sweets","sweets-2.jpeg"), bestseller: true,
      name: { ar: "حلو شرقي النجمة 1 كغ", he: "מתוק מזרחי כוכב 1 ק\"ג" },
      desc: { ar: "تشكيلة حلويات شرقية فاخرة على شكل نجمة لأرقى المناسبات.", he: "מגוון מתוקים מזרחיים משובחים בצורת כוכב לאירועים מיוחדים." } },
    { id: "swt-3", cat: "sweets", unit: "piece", price: 100, img: im("sweets","sweets-3.jpeg"),
      name: { ar: "حلو شرقي 550غ", he: "מתוק מזרחי 550 גרם" },
      desc: { ar: "تشكيلة حلويات شرقية متنوّعة بحجم عائلي مناسب.", he: "מגוון מתוקים מזרחיים בגודל משפחתי נוח." } },
    { id: "swt-4", cat: "sweets", unit: "piece", price: 150, img: im("sweets","sweets-4.jpeg"),
      name: { ar: "حلو شرقي حبيبة 750غ", he: "מתוק מזרחי חביבה 750 גרם" },
      desc: { ar: "تشكيلة حلويات حبيبة الشرقية الفاخرة بأنواع متعدّدة.", he: "מגוון מתוקי חביבה מזרחיים משובחים בסוגים שונים." } },
    { id: "swt-5", cat: "sweets", unit: "piece", price: 70,  img: im("sweets","sweets-5.jpeg"),
      name: { ar: "غريبة", he: "עוגיות ע'ריבה" },
      desc: { ar: "غريبة هشّة تذوب في الفم بنكهة السمن الأصيلة.", he: "ע'ריבה פריכה שנמסה בפה בטעם חמאה אותנטי." } },
    { id: "swt-6", cat: "sweets", unit: "piece", price: 110, img: im("sweets","sweets-6.jpeg"),
      name: { ar: "مشكّل برازق وغريبة ومعمول", he: "מארז בראזק, ע'ריבה ומעמול" },
      desc: { ar: "تشكيلة مشكّلة من البرازق والغريبة والمعمول الفاخر.", he: "מארז משולב של בראזק, ע'ריבה ומעמול משובח." } },
    { id: "swt-7", cat: "sweets", unit: "piece", price: 70,  img: im("sweets","sweets-7.jpeg"),
      name: { ar: "مشكّل غريبة وبرازق", he: "מארז ע'ריבה ובראזק" },
      desc: { ar: "تشكيلة من الغريبة والبرازق بمذاق شامي أصيل.", he: "מארז ע'ריבה ובראזק בטעם שאמי אותנטי." } },
    { id: "swt-8", cat: "sweets", unit: "piece", price: 110, img: im("sweets","sweets-8.jpeg"),
      name: { ar: "مشكّل معمول", he: "מארז מעמול" },
      desc: { ar: "معمول محشي بالتمر والجوز والفستق، حلوى العيد الأصيلة.", he: "מעמול במילוי תמרים, אגוזים ופיסטוק, ממתק החג האותנטי." } },

    /* ---------------- SNACKS (by weight) ---------------- */
    { id: "snk-1", cat: "snacks", unit: "kg", price: 45, img: im("snacks","snacks-1.jpeg"),
      name: { ar: "بندقية", he: "בונדוקייה" },
      desc: { ar: "حلوى البندقية المقرمشة بالسمسم والمكسرات، تسالي تقليدية.", he: "ממתק בונדוקייה פריך עם שומשום ואגוזים, נשנוש מסורתי." } },
    { id: "snk-2", cat: "snacks", unit: "kg", price: 45, img: im("snacks","snacks-2.jpeg"),
      name: { ar: "جوز الهند", he: "ממתק קוקוס" },
      desc: { ar: "حلوى جوز الهند بنكهتها الاستوائية الحلوة والمميّزة.", he: "ממתק קוקוס בטעם טרופי מתוק ומיוחד." } },
    { id: "snk-3", cat: "snacks", unit: "kg", price: 45, img: im("snacks","snacks-3.jpeg"),
      name: { ar: "سكاكر ألوان", he: "סוכריות צבעוניות" },
      desc: { ar: "سكاكر ملوّنة متنوّعة تسعد الكبار والصغار.", he: "סוכריות צבעוניות מגוונות לשמחת קטנים וגדולים." } },
    { id: "snk-4", cat: "snacks", unit: "kg", price: 45, img: im("snacks","snacks-4.jpeg"),
      name: { ar: "سمسمية", he: "סומסומיה" },
      desc: { ar: "سمسمية بالسمسم والعسل، حلوى طاقة تقليدية لذيذة.", he: "סומסומיה עם שומשום ודבש, ממתק אנרגיה מסורתי וטעים." } },
    { id: "snk-5", cat: "snacks", unit: "kg", price: 45, img: im("snacks","snacks-5.jpeg"),
      name: { ar: "عين الشمس", he: "חטיף עין השמש" },
      desc: { ar: "حلوى عين الشمس بالبزر، مقرمشة وغنية بالطاقة.", he: "חטיף עין השמש עם גרעינים, פריך ועשיר באנרגיה." } },

    /* ---------------- GUMMY (by weight) ---------------- */
    { id: "gum-1", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-19.jpeg"),
      name: { ar: "حلوى جيلي مشكّلة", he: "סוכריות גומי מעורבות" },
      desc: { ar: "حلوى جيلي مشكّلة بأشكال وألوان ونكهات فواكه متنوّعة.", he: "סוכריות גומי מעורבות בצורות, צבעים וטעמי פירות." } },
    { id: "gum-2", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-1.jpeg"),
      name: { ar: "جيلي دببة", he: "גומי דובונים" },
      desc: { ar: "جيلي على شكل دببة بنكهات فواكه حلوة ومرحة.", he: "גומי דובונים בטעמי פירות מתוקים ומשמחים." } },
    { id: "gum-3", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-2.jpeg"),
      name: { ar: "جيلي حلقات", he: "גומי טבעות" },
      desc: { ar: "جيلي حلقات بنكهة الفواكه ومذاق منعش.", he: "גומי טבעות בטעם פירות ובמרקם מרענן." } },
    { id: "gum-4", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-3.jpeg"),
      name: { ar: "جيلي فواكه", he: "גומי פירות" },
      desc: { ar: "جيلي فواكه متنوّع بألوان زاهية ونكهات طبيعية.", he: "גומי פירות מגוון בצבעים עזים ובטעמים." } },
    { id: "gum-5", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-4.jpeg"),
      name: { ar: "جيلي ديدان", he: "גומי תולעים" },
      desc: { ar: "جيلي ديدان مرح بنكهات فواكه ثنائية اللون.", he: "גומי תולעים משעשע בטעמי פירות דו-צבעיים." } },
    { id: "gum-6", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-5.jpeg"),
      name: { ar: "جيلي كولا", he: "גומי קולה" },
      desc: { ar: "جيلي بنكهة الكولا المنعشة بشكله الكلاسيكي.", he: "גומי בטעם קולה מרענן בצורתו הקלאסית." } },
    { id: "gum-7", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-6.jpeg"),
      name: { ar: "جيلي قلوب", he: "גומי לבבות" },
      desc: { ar: "جيلي على شكل قلوب بنكهات فواكه حلوة ورومانسية.", he: "גומי לבבות בטעמי פירות מתוקים." } },
    { id: "gum-8", cat: "gummy", unit: "kg", price: 45, img: im("gummy","gummy-7.jpeg"),
      name: { ar: "جيلي حامض", he: "גומי חמוץ" },
      desc: { ar: "جيلي حامض بطبقة سكر لاذعة ونكهات فواكه قويّة.", he: "גומי חמוץ בציפוי סוכר חמצמץ ובטעמי פירות עזים." } }
  ];

  // Delivery rules — fee in shekels keyed by normalized city/village.
  const DELIVERY = {
    near: { fee: 10, places: ["مقيبلة", "מוקייבלה", "muqeible", "مقيبله", "صندلة", "סנדלה", "sandala", "صندله"] },
    far: { fee: 30 },
    pickup: { fee: 0 }
  };

  window.AdamData = { STORE, WEIGHTS, CATEGORIES, PRODUCTS, DELIVERY };
})();
